using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;
using System.Threading.Tasks;

namespace RemoveCustomFemaleBodies
{
    public class Program
    {
        // Populated by SetAutogeneratedSettings before RunPatch ever runs.
        private static Settings _settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "RemoveCustomFemaleBodies.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            int patchedCount = 0;

            foreach (var npcGetter in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                // Skip NPCs whose base record comes from an excluded (default: vanilla) plugin
                if (_settings.ExcludedMods.Contains(npcGetter.FormKey.ModKey))
                    continue;

                // Only female NPCs
                if (!npcGetter.Configuration.Flags.HasFlag(NpcConfiguration.Flag.Female))
                    continue;

                // Optionally skip children - different skeleton/body, forcing an adult
                // skin onto them looks wrong or can break entirely
                if (_settings.SkipChildren
                    && npcGetter.Race.FormKey == Skyrim.Race.SkyrimChildRace.FormKey)
                    continue;

                // Nothing to strip if there's no custom skin override already
                if (npcGetter.WornArmor.IsNull)
                    continue;

                // Clear the override so the NPC falls back to their Race's default
                // skin - the one your body/texture mod replaces
                var npc = state.PatchMod.Npcs.GetOrAddAsOverride(npcGetter);
                npc.WornArmor.SetToNull();
                patchedCount++;
            }

            System.Console.WriteLine($"Removed custom body/skin overrides from {patchedCount} female NPCs.");
        }
    }
}
